global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: scraper
    static_configs:
      - targets: ["scraper:2112"]
  - job_name: matcher
    static_configs:
      - targets: ["matcher:2113"]
  - job_name: bot
    static_configs:
      - targets: ["bot:2114"]
